spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:oracle:thin:@zhosck61umxnno3x_high?TNS_ADMIN:classpath:/Users/austin/Documents/austin/private/project/practiceProject/burning-house/burning-house-user/src/main/resources/Wallet_ZHOSCK61UMXNNO3X
    username: admin
    password: Burning1234!
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      max-lifetime: 240000
      pool-name: oraPool
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
  logging:
    level:
      org:
        springframework:
          web:
            servlet: debug;
  output:
    ansi:
      enabled: always